### ISSUE TITLE
remove from history book ended

### ISSUE THREAD

**Issue by panaC** [edrlab/lis-mon-livre#43]

**Comment by panaC** [comment]
possible feature : 

obtenir l'historique de lecture qui est différents de lecture en cours

historique : tout les livre en reverse order
lecture en cours : tout les livre en reverse order qui ne sont pas terminés

**Comment by llemeurfr** [comment]
Je ne pense pas qu'on puisse savoir quand un livre est terminé. 
Si l'on veut nettoyer l'historique des livres récents, autant "couper" après 3 mois depuis la dernière lecture.

**Comment by panaC** [comment]
L'information de fin de lecture est disponible
