### ISSUE TITLE
CELA Google, répétition sur le help liste titres

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/lis-mon-livre#60]
CELA dev

Je demande les collections de type genre, je choisis un genre, j'écoute les trois titres, mais je ne réponds pas. 
Le message d'aide est alors ...

selection/help/1 
suivi de selection/common/1
puis une boucle sur selection/common/2
et enfin selection/common/3
 
Est-ce qu'il serait possible de ne pas lire selection/common/1, qui est un peu redondant ?

**Comment by llemeurfr** [comment]
en passant, selection/help/2 ne semble jamais joué. Si c'est le cas autant le supprimer.

**Comment by panaC** [comment]
si tu peux le corriger dans ta PR please 👍 

Sinon dis moi si je dois intervenir dans le code

**Comment by llemeurfr** [comment]
Il faudrait d'abord vérifier que selection/help/2 n'est réellement joué : est-ce possible ? ou faut-il le supprimer et voir si des tests ratent ?

**Comment by panaC** [comment]
https://github.com/edrlab/lis-mon-livre/blob/9442e82c1f35db1435b9d5f9a44cd6c004cecf8c/webhooks/functions/src/controller/handler/selection.ts#L202

commenté

**Comment by llemeurfr** [comment]
ok alors je le retire du dialogue dans ma PR.

**Comment by panaC** [comment]
> Est-ce qu'il serait possible de ne pas lire selection/common/1, qui est un peu redondant ?


Le mieux est de tweaker le help 

car le flux est fallback -> help -> on-enter

**Comment by llemeurfr** [comment]
Alors fermons cette issue pour le moment, car je n'ai pas d'idée. On verra les retours des testeurs.
