### ISSUE TITLE
collections, repetition si type collection non compris

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/lis-mon-livre#67]
Quand l'assistant demande si je désire des collections par thème ou par genre, je réponds mal (ex. "by toto"). 

J'entends alors collections/help/1 suivi de collections/enter/1. 
Le second est en trop. 
Soit on peut le supprimer, soit il faut revoir le message d'aide (supprimer la seconde phrase).
La seconde solution est peut être la plus simple ?

 "collections": {
    "enter": {
      "1": "Okay, would you prefer to get a choice of collections by theme or by genre?"
    },
    "help": {
      "1": "To hear an overview of available themes, say 'theme'. For an overview of available genres, say 'genre'. Do you want to hear a list of available themes or genres?"
    }
  },

**Comment by panaC** [comment]
oui il faut supprimer la seconde phrase dans help !

**Comment by panaC** [comment]
Peut-tu le faire dans ta PR please 👍

**Comment by llemeurfr** [comment]
Je l'ai fait d'office.

**Comment by panaC** [comment]
#68
