### ISSUE TITLE
Les collections CELA en français n'apparaissent pas, on accède aux collection anglaises

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/lis-mon-livre#70]
CELA a mis en place des collections en français (par genre et par thème). L'attribut langue est censé permettre de choisir les unes ou les autres à partir du même endpoint. 
Mais l'expérience ne fonctionne ni sur l'app Google ni sur l'app Alexa. 
A vérifier si l'API fonctionne comme prévu, et si oui pourquoi l'attribut langue ne fonctionne pas.

**Comment by panaC** [comment]
api didn't handle accept-language spécification

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language

**Comment by llemeurfr** [comment]
Not really true. It is only accepting simple forms like "fr" but not "fr-FR" or "fr-CA", that we are using. 
Will be updated at the API level.

**Comment by panaC** [comment]
fixes https://github.com/edrlab/lis-mon-livre/commit/2ff9e0625b64b05c4ffda8183c0d340ad04d81b0
